app:
    jwtExpirationInMs: 604800000
    jwtSecret: JWTKeySecret
    jwtType: Bearer
    oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
      authorizedRedirectUris: http://localhost:4200/profile,myandroidapp://oauth2/redirect,myiosapp://oauth2/redirect
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/socialappdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        password: password
        username: root
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                enab  le_lazy_load_no_trans: true
        show-sql: true
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: GoogleAppClientId
              clientSecret: GoogleAppClientSecret
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
            facebook:
              clientId: FacebookAppClientId
              clientSecret: FacebookAppClientSecret
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}" 
              scope:
                - email
                - public_profile
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
    
